"""repuestos

Revision ID: 57aaf780a4a3
Revises: 6717ccbe1b47
Create Date: 2025-01-05 11:42:42.330280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57aaf780a4a3'
down_revision = '6717ccbe1b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud_repuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_maquina', sa.Integer(), nullable=False),
    sa.Column('nivel_urgencia', sa.String(length=50), nullable=False),
    sa.Column('justificacion', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_maquina'], ['maquinaria.id_maquinaria'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitud_repuesto')
    # ### end Alembic commands ###
