"""Add titulos

Revision ID: 6717ccbe1b47
Revises: a297f71ad806
Create Date: 2024-10-05 12:01:00.448468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6717ccbe1b47'
down_revision = 'a297f71ad806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titulos',
    sa.Column('id_titulo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_titulo')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_titulo', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'titulos', ['id_titulo'], ['id_titulo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_titulo')

    op.drop_table('titulos')
    # ### end Alembic commands ###
