"""Notificacoines

Revision ID: 6a2a15edf58b
Revises: 57aaf780a4a3
Create Date: 2025-01-05 16:17:46.250796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a2a15edf58b'
down_revision = '57aaf780a4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuraciones_notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('smtp_server', sa.String(length=100), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('solicitud_repuesto')
    op.drop_table('configuraciones')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuraciones',
    sa.Column('id_configuracion', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo_notificacion', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('valor_correo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('valor_whatsapp', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_configuracion', name='configuraciones_pkey')
    )
    op.create_table('solicitud_repuesto',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_maquina', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nivel_urgencia', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('justificacion', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_maquina'], ['maquinaria.id_maquinaria'], name='solicitud_repuesto_id_maquina_fkey'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='solicitud_repuesto_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id', name='solicitud_repuesto_pkey')
    )
    op.drop_table('configuraciones_notificaciones')
    # ### end Alembic commands ###
