"""actualizacion

Revision ID: 860bc5abc504
Revises: a3aafefec603
Create Date: 2024-10-04 10:47:11.268660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860bc5abc504'
down_revision = 'a3aafefec603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mantenimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiempo_requerido', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mantenimientos', schema=None) as batch_op:
        batch_op.drop_column('tiempo_requerido')

    # ### end Alembic commands ###
