"""Initial migration

Revision ID: a3aafefec603
Revises: 
Create Date: 2024-09-30 19:24:44.645020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3aafefec603'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuraciones',
    sa.Column('id_configuracion', sa.Integer(), nullable=False),
    sa.Column('tipo_notificacion', sa.String(length=50), nullable=False),
    sa.Column('valor_correo', sa.String(length=100), nullable=True),
    sa.Column('valor_whatsapp', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_configuracion')
    )
    op.create_table('herramientas',
    sa.Column('id_herramienta', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('h_imagen', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_herramienta')
    )
    op.create_table('maquinaria',
    sa.Column('id_maquinaria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('numero_serie', sa.String(length=255), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('m_imagen', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_maquinaria'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=50), nullable=False),
    sa.Column('cedula', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('genero', sa.String(length=10), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('foto', sa.LargeBinary(), nullable=True),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('estado_usuario', sa.String(length=50), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accesos',
    sa.Column('id_acceso', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('acceso_boole', sa.Boolean(), nullable=False),
    sa.Column('fecha_acceso', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_acceso')
    )
    op.create_table('contactos',
    sa.Column('id_contacto', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('convencional', sa.String(length=15), nullable=True),
    sa.Column('celular', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('parentesco', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_contacto')
    )
    op.create_table('mantenimientos',
    sa.Column('id_mantenimiento', sa.Integer(), nullable=False),
    sa.Column('id_maquinaria', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_mantenimiento', sa.String(length=100), nullable=False),
    sa.Column('fecha_mantenimiento', sa.DateTime(), nullable=False),
    sa.Column('proxima_fecha', sa.DateTime(), nullable=False),
    sa.Column('frecuencia', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('estado_actual', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_maquinaria'], ['maquinaria.id_maquinaria'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_mantenimiento')
    )
    op.create_table('historial_estados',
    sa.Column('id_historial_estado', sa.Integer(), nullable=False),
    sa.Column('id_mantenimiento', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('fecha_estado', sa.DateTime(), nullable=True),
    sa.Column('es_estado_actual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_mantenimiento'], ['mantenimientos.id_mantenimiento'], ),
    sa.PrimaryKeyConstraint('id_historial_estado')
    )
    op.create_table('mantenimiento_herramienta',
    sa.Column('id_mantenimiento', sa.Integer(), nullable=False),
    sa.Column('id_herramienta', sa.Integer(), nullable=False),
    sa.Column('cantidad_usada', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_herramienta'], ['herramientas.id_herramienta'], ),
    sa.ForeignKeyConstraint(['id_mantenimiento'], ['mantenimientos.id_mantenimiento'], ),
    sa.PrimaryKeyConstraint('id_mantenimiento', 'id_herramienta')
    )
    op.create_table('notificaciones',
    sa.Column('id_notificacion', sa.Integer(), nullable=False),
    sa.Column('id_mantenimiento', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('estado_envio', sa.String(length=50), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_mantenimiento'], ['mantenimientos.id_mantenimiento'], ),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificaciones')
    op.drop_table('mantenimiento_herramienta')
    op.drop_table('historial_estados')
    op.drop_table('mantenimientos')
    op.drop_table('contactos')
    op.drop_table('accesos')
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('maquinaria')
    op.drop_table('herramientas')
    op.drop_table('configuraciones')
    # ### end Alembic commands ###
